# WDI - WORLD DEVELOPMENT INDICATORS
# BASE DE DADOS DO BANCO MUNDIAL

#install.packages("WDI")
library(WDI)
# SEMPRE PROCUREM AS VIGNETES 
# PÁGINAS COM ORIENTAÇÕES DOS PACOTES

# BAIXAR OS DADOS DO PIB (PRODUTO INTERNO BRUTO)
# TUDO QUE É PRODUZIDO EM UM PAÍS/ESTADO/MUN.
# EM UM DETERMINADO PERÍODO

# GDP (current US$)(NY.GDP.MKTP.CD)
# GROSS DOMESTIC PRODUCT (GDP) EM DÓLARES NORTE-AMERICANOS 
# CÓDIGO NY.GDP.MKTP.CD

COD_GDP <- WDIsearch('gdp')
# É IMPORTANTE PROCURAR PELO PRÓPRIO SITE DO BANCO MUNDIAL, É MAIS EFICIENTE

# COM O CÓDIGO, VAMOS BAIXAR OS DADOS

basepib <- WDI(country = 'all', indicator = 'NY.GDP.MKTP.CD')

# COM O CÓDIGO, VAMOS BAIXAR OS DADOS

options(scipen = 999) # AJUSTAR OS NÚMEROS (NOT. CIENT.)

basepib2023 <- WDI(country = 'all', indicator = 'NY.GDP.MKTP.CD', start = 2023, end = 2023)
